package com.datamodule.models.enums;

public enum TaskMessage {
    NEW_TASK, FINISH_TASK, DO_TASK, UPDATE_TASK, UPDATE_PRIORITY_TASKS,
    DO_NODE_TASK, NEW_NODE_TASK, UPDATE_PRIORITY_TASK_NODES, UPDATE_TASK_NODES
}
